// RESPONSE CODE
export const RESPONSE_CODE_SUCCESS = 200
export const RESPONSE_CODE_INTERNAL_SERVER_ERROR = 500
export const RESPONSE_CODE_NOT_FOUND = 404
export const RESPONSE_CODE_BAD_REQUEST = 400
export const RESPONSE_CODE_UNAUTHORIZED = 403

// RESPONSE MESSAGE
export const RESPONSE_MESSAGE_ACCESS_TOKEN_NOT_FOUND = "User Access Token Not Found"
export const RESPONSE_MESSAGE_UNAUTHORIZED = "User Access Token Unauthorized"
export const RESPONSE_MESSAGE_BAD_REQUEST = "Invalid Schemas Request"
export const RESPONSE_MESSAGE_SUCCESS = "Success"
export const RESPONSE_MESSAGE_NOT_FOUND = "Data Not Found"
export const RESPONSE_MESSAGE_ROUTE_NOT_FOUND = "Route Not Found"
export const RESPONSE_MESSAGE_INTERNAL_SERVER_ERROR = "Internal Server Error"

// SERVICES
export const ROUTES_WITHOUT_NAVIGATOR = ["/login", "/register", "/404", "/verifikasi-email"]

// CLIENT URL PATH LISTS
export const CLIENT_ROUTES_WITHOUT_TOKEN = ["/login", "/register", "/", "/download", "/faq", "/contact", "/404", "/verifikasi-email"]
export const CLIENT_PATH = {
  BASE: "/",
  NOT_FOUND: "/404",
  LOGIN: "/login",
  REGISTER: "/register",
  DASHBOARD: "/dashboard",
  DOWNLOAD: "/download",
  FAQ: "/faq",
  CONTACT: "/contact",
  PROFILE: "/profile",
  VERIFIKASI_EMAIL: "/verifikasi-email",
  FORM_PENDAFTARAN: "/form-pendaftaran",
  UBAH_PASSWORD: "/ubah-password",
  BANTUAN: "/bantuan",
}

// API URL LISTS
export const API_ROUTES_WITHOUT_TOKEN = ["/api/auth/login", "/api/auth/register", "/api/auth/verifikasi-email"]
export const API_PATH = {
  AUTH_LOGIN: "/api/auth/login",
  AUTH_REGISTER: "/api/auth/register",
  AUTH_VERIFIKASI_EMAIL: "/api/auth/verifikasi-email",
  AUTH_LOGOUT: "/api/auth/logout",
  LIST_EDUCATION: "/api/list/education",
  LIST_JURUSAN: "/api/list/jurusan",
  NOTIFICATION: "/api/notification",
  UPDATE_NOTIFICATION: "/api/notification/update-status",
  USER_PROFILE: "/api/user/profile",
  STATUS_PENDAFTARAN: "/api/user/status-pendaftaran",
  USER_FORM_PENDAFTARAN: "/api/user/form-pendaftaran",
  USER_PENGAJUAN_PENDAFTARAN: "/api/user/pengajuan-pendaftaran",
  TEST_EMAIL: "/api/test-email",
}

// CLIENT ANY URL LIST
export const CLIENT_URL_WHATSAPP = "https://api.whatsapp.com/send?phone=6282113785144&text=Assalamualaikum%20Admin%20PMB%20PKUMI%20Saya%20mau%20konsultasi"
export const CLIENT_URL_MAPS_LOCATION =
  "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3966.7055307599117!2d106.82920131476892!3d-6.170169995532885!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e69f5ce68b5e01d%3A0xcafaf042d5840c6c!2sMasjid%20Istiqlal!5e0!3m2!1sid!2sid!4v1597032173552!5m2!1sid!2sid"

// ENUMERATION TYPE LISTS
export const ENUMERATION_TYPE_USERS_TYPE = "UT"
export const ENUMERATION_TYPE_WS_LOG = "WS"
export const ENUMERATION_TYPE_REGISTRATION_STATUS = "RS"
export const ENUMERATION_TYPE_STUDY_LEVEL = "SL"

// ENUMERATION LISTS
export const ENUMERATION_USERS_TYPE_ADMIN = "UT-001"
export const ENUMERATION_USERS_TYPE_MAHASISWA = "UT-002"
export const ENUMERATION_USERS_TYPE_DOSEN = "UT-003"
export const ENUMERATION_SERVICE_REGISTER = "WS-001"
export const ENUMERATION_SERVICE_LOGIN = "WS-002"
export const ENUMERATION_SERVICE_VERIFIKASI_EMAIL = "WS-003"
export const ENUMERATION_SERVICE_UPDATE_PROFILE = "WS-004"
export const ENUMERATION_SERVICE_UPDATE_STATUS_NOTIFICATION = "WS-005"
export const ENUMERATION_SERVICE_UPDATE_STATUS_PEMBERKASAN = "WS-006"
export const ENUMERATION_SERVICE_UPDATE_STATUS_WAWANCARA = "WS-007"
export const ENUMERATION_SERVICE_UPDATE_JADWAL_WAWANCARA = "WS-008"
export const ENUMERATION_SERVICE_UPDATE_FORM_PENDAFTARAN = "WS-009"
export const ENUMERATION_SERVICE_PENGAJUAN_PENDAFTARAN = "WS-010"
export const ENUMERATION_SERVICE_UPDATE_KETERANGAN_WAWANCARA = "WS-011"
export const ENUMERATION_SERVICE_UPDATE_STATUS_KELULUSAN = "WS-012"
export const ENUMERATION_SERVICE_UPDATE_DATA_LOA = "WS-013"
export const ENUMERATION_SERVICE_CREATE_MATA_KULIAH = "WS-014"
export const ENUMERATION_SERVICE_UPDATE_MATA_KULIAH = "WS-015"
export const ENUMERATION_SERVICE_DELETE_MATA_KULIAH = "WS-016"
export const ENUMERATION_SERVICE_UBAH_PASSWORD = "WS-017"
export const ENUMERATION_SERVICE_CREATE_LECTURER = "WS-018"
export const ENUMERATION_SERVICE_UPDATE_LECTURER = "WS-019"
export const ENUMERATION_SERVICE_DELETE_LECTURER = "WS-020"
export const ENUMERATION_SERVICE_CREATE_RUANGAN = "WS-021"
export const ENUMERATION_SERVICE_UPDATE_RUANGAN = "WS-022"
export const ENUMERATION_SERVICE_NONAKTIF_RUANGAN = "WS-023"
export const ENUMERATION_SERVICE_CREATE_SEMESTER = "WS-024"
export const ENUMERATION_SERVICE_CREATE_SCHEDULE = "WS-025"
export const ENUMERATION_SERVICE_UPDATE_SCHEDULE = "WS-026"
export const ENUMERATION_SERVICE_DELETE_SCHEDULE = "WS-027"
export const ENUMERATION_SERVICE_CREATE_JADWAL_KULIAH = "WS-028"
export const ENUMERATION_SERVICE_UPDATE_JADWAL_KULIAH = "WS-029"
export const ENUMERATION_SERVICE_DELETE_JADWAL_KULIAH = "WS-030"
export const ENUMERATION_SERVICE_SEND_STUDENT_LOA = "WS-031"
export const ENUMERATION_REGISTRATION_STATUS_BARU = "RS-001"
export const ENUMERATION_REGISTRATION_STATUS_MENGAJUKAN_BERKAS = "RS-002"
export const ENUMERATION_REGISTRATION_STATUS_DISETUJUI_BERKAS = "RS-003"
export const ENUMERATION_REGISTRATION_STATUS_DITOLAK_BERKAS = "RS-004"
export const ENUMERATION_REGISTRATION_STATUS_DIAJUKAN_KEMBALI_BERKAS = "RS-005"
export const ENUMERATION_REGISTRATION_STATUS_DIJADWALKAN_WAWANCARA = "RS-006"
export const ENUMERATION_REGISTRATION_STATUS_HADIR_WAWANCARA = "RS-007"
export const ENUMERATION_REGISTRATION_STATUS_TIDAK_HADIR_WAWANCARA = "RS-008"
export const ENUMERATION_REGISTRATION_STATUS_TIDAK_LULUS_PENDAFTARAN = "RS-009"
export const ENUMERATION_REGISTRATION_STATUS_MAHASISWA_AKTIF = "RS-010"

// STATUS WS LOG
export const WS_LOG_STATUS_NEW = "NEW"
export const WS_LOG_STATUS_DONE = "DONE"
export const WS_LOG_STATUS_FAILED = "FAILED"
export const WS_LOG_STATUS_ON_PROGGRES = "ON PROGRESS"

// STATUS PENDAFTARAN
export const STATUS_PENDAFTARAN_BARU = "BARU"
export const STATUS_PENDAFTARAN_MENGAJUKAN_BERKAS = "MENGAJUKAN_BERKAS"
export const STATUS_PENDAFTARAN_DISETUJUI_BERKAS = "DISETUJUI_BERKAS"
export const STATUS_PENDAFTARAN_DITOLAK_BERKAS = "DITOLAK_BERKAS"
export const STATUS_PENDAFTARAN_DIAJUKAN_KEMBALI_BERKAS = "DIAJUKAN_KEMBALI_BERKAS"
export const STATUS_PENDAFTARAN_DIJADWALKAN_WAWANCARA = "DIJADWALKAN_WAWANCARA"
export const STATUS_PENDAFTARAN_HADIR_WAWANCARA = "HADIR_WAWANCARA"
export const STATUS_PENDAFTARAN_TIDAK_HADIR_WAWANCARA = "TIDAK_HADIR_WAWANCARA"
export const STATUS_PENDAFTARAN_TIDAK_LULUS_PENDAFTARAN = "TIDAK_LULUS_PENDAFTARAN"
export const STATUS_PENDAFTARAN_MAHASISWA_AKTIF = "MAHASISWA_AKTIF"

// STATUS MAHASISWA
export const STATUS_MAHASISWA_REGISTRASI = "Registrasi"
export const STATUS_MAHASISWA_BELUM_LULUS = "Belum Lulus"
export const STATUS_MAHASISWA_LULUS = "Lulus"
export const STATUS_MAHASISWA_CUTI = "Cuti"
export const STATUS_MAHASISWA_TIDAK_AKTIF = "Tidak Aktif"

// ENUM CONTENT PMB
export const ENUMERATION_PMB_BERANDA = "Beranda"
export const ENUMERATION_PMB_DOWNLOAD = "Download"
export const ENUMERATION_PMB_FAQ = "FAQ"
export const ENUMERATION_PMB_CONTACT = "Contact"

// ANY
export const HEADERS_TOKEN_DATA_NAME = "token-data"

// PKUMI DATA
export const PKUMI_LOGO_PASCASARJANA = "/images/logo-pascasarjana.png"
export const PKUMI_ADDRESS_STREET_NAME = "Jl. Lebak Bulus Raya No.2"
export const PKUMI_ADDRESS_WARD = "Lebak Bulus"
export const PKUMI_ADDRESS_SUBDISTRICT = "Cilandak"
export const PKUMI_ADDRESS_CITY = "Jakarta Selatan"
export const PKUMI_ADDRESS_POSTAL_CODE = "12440"
export const PKUMI_PASCASARJANA_URL = "https://pascasarjana-ptiq.ac.id"
export const PKUMI_EMAIL = "pasca@ptiq.ac.id"
export const PKUMI_TELP = "(021) 75904826 (ext-113)"
export const PKUMI_LOA_ANNOUNCEMENT_NUMBER = "032/PTIQ.A/Km/Kep/VI/2023"
export const PKUMI_WHATSAPP_PMB = "+62 821-1378-5144"
export const PKUMI_EMAIL_PMB = "pmb@istiqlal.or.id"
